name: flutter_lapor_book
description: "Proyek Lapor Book."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-174.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.19.0
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
 
  flutter_launcher_icons: ^0.13.1

    # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5

flutter_icons:
  image_path: "assets/Logo.png" 
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
