// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSkdOhTe_mbK14P53EpKo_kOJAMH8HOw',
    appId: '1:210022109562:web:5196c0f46abe0b07ccc6c3',
    messagingSenderId: '210022109562',
    projectId: 'lapor-book',
    authDomain: 'lapor-book.firebaseapp.com',
    storageBucket: 'lapor-book.appspot.com',
    measurementId: 'G-1GHZSJK9RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NwHWOPoqpQ36rh4e2N68jsd8d5rtaqQ',
    appId: '1:210022109562:android:64f56fbb821b4d67ccc6c3',
    messagingSenderId: '210022109562',
    projectId: 'lapor-book',
    storageBucket: 'lapor-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkzSRTEsWANvJzWBMwooZTZgD0gD-aosw',
    appId: '1:210022109562:ios:1d1f54a0068c1415ccc6c3',
    messagingSenderId: '210022109562',
    projectId: 'lapor-book',
    storageBucket: 'lapor-book.appspot.com',
    iosBundleId: 'com.example.flutterKeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkzSRTEsWANvJzWBMwooZTZgD0gD-aosw',
    appId: '1:210022109562:ios:1599a0ccb256371fccc6c3',
    messagingSenderId: '210022109562',
    projectId: 'lapor-book',
    storageBucket: 'lapor-book.appspot.com',
    iosBundleId: 'com.example.flutterKeuangan.RunnerTests',
  );
}
