// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Mq-mzIVJtulTXiZP6z-t8GJLZ47JGmc',
    appId: '1:134236590361:web:a9ec1294e44edca561b588',
    messagingSenderId: '134236590361',
    projectId: 'lapor-book-9db05',
    authDomain: 'lapor-book-9db05.firebaseapp.com',
    storageBucket: 'lapor-book-9db05.appspot.com',
    measurementId: 'G-KPSRWQ1HTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb6_8Q68N_wTABnxODRkFmgwQnuy_bs7c',
    appId: '1:134236590361:android:26429723890c24f161b588',
    messagingSenderId: '134236590361',
    projectId: 'lapor-book-9db05',
    storageBucket: 'lapor-book-9db05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLaKU1WEniHxKs1pNuScwBZ_5MdRpNkYM',
    appId: '1:134236590361:ios:c46b4299fc47a0b961b588',
    messagingSenderId: '134236590361',
    projectId: 'lapor-book-9db05',
    storageBucket: 'lapor-book-9db05.appspot.com',
    iosBundleId: 'com.example.flutterKeuangan',
  );
}
